---
- name: Copying over ceph.conf(s)
  merge_configs:
    sources:
      - "{{ role_path }}/../ceph/templates/ceph.conf.j2"
      - "{{ node_custom_config }}/ceph.conf"
      - "{{ node_custom_config }}/ceph/{{ inventory_hostname }}/ceph.conf"
    dest: "{{ node_config_directory }}/glance-api/ceph.conf"
    mode: "0660"
  become: true
  when:
    - glance_services['glance-api'].host_in_groups | bool
    - glance_services['glance-api'].enabled | bool
  notify:
    - Restart glance-api container

- include_tasks: ../../ceph_pools.yml
  vars:
    pool_name: "{{ glance_pool_name }}"
    pool_type: "{{ glance_pool_type }}"
    cache_mode: "{{ glance_cache_mode }}"
    pool_pg_num: "{{ glance_pool_pg_num }}"
    pool_pgp_num: "{{ glance_pool_pgp_num }}"
    pool_application: "rbd"

- name: Pulling cephx keyring
  become: true
  kolla_ceph_keyring:
    name: client.glance
    caps: "{{ ceph_client_glance_keyring_caps }}"
  register: cephx_key
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  run_once: True

- name: Pushing cephx keyring
  copy:
    content: |
      [client.glance]
          key = {{ cephx_key.keyring.key }}
    dest: "{{ node_config_directory }}/glance-api/ceph.client.glance.keyring"
    mode: "0600"
  become: true
  when:
    - glance_services['glance-api'].host_in_groups | bool
    - glance_services['glance-api'].enabled | bool
  notify:
    - Restart glance-api container

- name: Ensuring config directory has correct owner and permission
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  when:
    - glance_services[item].host_in_groups | bool
    - glance_services[item].enabled | bool
  with_items:
    - "glance-api"
