---
- name: Copy over ceph files
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/glance-api/"
    mode: "0660"
  become: true
  when:
    - glance_services['glance-api'].host_in_groups | bool
    - glance_services['glance-api'].enabled | bool
  with_fileglob:
    - "{{ node_custom_config }}/glance/ceph*"
  notify:
    - Restart glance-api container

- name: Ensuring config directory has correct owner and permission
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  become: true
  when:
    - glance_services[item].host_in_groups | bool
    - glance_services[item].enabled | bool
  with_items:
    - "glance-api"
