---
- name: Pulling glance images
  become: true
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ item.value.image }}"
  when:
    - item.value.host_in_groups | bool
    - item.value.enabled | bool
  with_dict: "{{ glance_services }}"
