---
project_name: "multipathd"

multipathd_services:
  multipathd:
    container_name: multipathd
    group: multipathd
    enabled: true
    ipc_mode: "host"
    privileged: True
    image: "{{ multipathd_image_full }}"
    volumes:
      - "{{ node_config_directory }}/multipathd/:{{ container_config_directory }}/:ro"
      - "kolla_logs:/var/log/kolla/"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/run/:/run/:shared"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/sys/kernel/config:/configfs"
      - "cinder:/var/lib/cinder"
      - "iscsi_info:/etc/iscsi"


####################
# Docker
####################
multipathd_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-multipathd"
multipathd_tag: "{{ openstack_release }}"
multipathd_image_full: "{{ multipathd_image }}:{{ multipathd_tag }}"
