---
project_name: "panko"

panko_services:
  panko-api:
    container_name: panko_api
    group: panko-api
    enabled: true
    image: "{{ panko_api_image_full }}"
    volumes: "{{ panko_api_default_volumes + panko_api_extra_volumes }}"
    dimensions: "{{ panko_api_dimensions }}"
    haproxy:
      panko_api:
        enabled: "{{ enable_panko }}"
        mode: "http"
        external: false
        port: "{{ panko_api_port }}"
      panko_api_external:
        enabled: "{{ enable_panko }}"
        mode: "http"
        external: true
        port: "{{ panko_api_port }}"


####################
# Database
####################
panko_database_name: "panko"
panko_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}panko{% endif %}"
panko_database_port: "{{ mongodb_port if panko_database_type == 'mongodb' else database_port }}"
panko_database_mongodb_address: "{% for host in groups['mongodb'] %}{{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }}:{{ panko_database_port }}{% if not loop.last %},{% endif %}{% endfor %}"
panko_database_mysql_address: "{{ database_address }}:{{ database_port }}"

####################
# Docker
####################
panko_install_type: "{{ kolla_install_type }}"
panko_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ panko_install_type }}-panko-api"
panko_api_tag: "{{ openstack_release }}"
panko_api_image_full: "{{ panko_api_image }}:{{ panko_api_tag }}"
panko_api_dimensions: "{{ default_container_dimensions }}"

panko_api_default_volumes:
  - "{{ node_config_directory }}/panko-api/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "kolla_logs:/var/log/kolla/"
panko_api_extra_volumes: "{{ default_extra_volumes }}"

####################
# OpenStack
####################
panko_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ panko_api_port }}"
panko_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ panko_api_port }}"
panko_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ panko_api_port }}"

panko_logging_debug: "{{ openstack_logging_debug }}"

panko_keystone_user: "panko"

openstack_panko_auth: "{{ openstack_auth }}"
