---
- name: Creating admin project, user, role, service, and endpoint
  become: true
  command: docker exec keystone kolla_keystone_bootstrap {{ openstack_auth.username }} {{ openstack_auth.password }} {{ openstack_auth.project_name }} admin {{ keystone_admin_url }} {{ keystone_internal_url }} {{ keystone_public_url }} {{ item }}
  register: keystone_bootstrap
  changed_when: (keystone_bootstrap.stdout | from_json).changed
  failed_when: (keystone_bootstrap.stdout | from_json).failed
  run_once: True
  with_items: "{{ multiple_regions_names }}"

# NOTE(jeffrey4l): Since keystone-manage bootstrap cloud not update the endpoint,
# run kolla_keystone_service module again.
- name: Creating the Keystone service and endpoint
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_service"
    module_args:
      service_name: "keystone"
      service_type: "identity"
      description: "Openstack Identity Service"
      endpoint_region: "{{ openstack_region_name }}"
      url: "{{ item.url }}"
      interface: "{{ item.interface }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_keystone_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
  with_items:
    - { interface: admin, url: "{{ keystone_admin_url }}" }
    - { interface: internal, url: "{{ keystone_internal_url }}" }
    - { interface: public, url: "{{ keystone_public_url }}" }

- name: Creating default user role
  become: true
  kolla_toolbox:
    module_name: "os_keystone_role"
    module_args:
      name: "{{ keystone_default_user_role }}"
      auth: "{{ openstack_keystone_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
