---
- include_tasks: register.yml
  when: inventory_hostname in groups['karbor-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['karbor-api'] or
        inventory_hostname in groups['karbor-protection'] or
        inventory_hostname in groups['karbor-operationengine']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['karbor-api']

- name: Flush handlers
  meta: flush_handlers
