---
- name: Warn about deprecation
  debug:
    msg: >-
      Support for deploying Ceph via Kolla Ansible is deprecated. In a future
      release support for deploying Ceph will be removed from Kolla Ansible. Prior
      to this we will ensure a migration path to another tool such as Ceph
      Ansible (http://docs.ceph.com/ceph-ansible/master/>) is available. For new
      deployments it is recommended to use another tool to deploy Ceph to avoid a
      future migration. This can be integrated with OpenStack by following the
      external Ceph guide
      (https://docs.openstack.org/kolla-ansible/latest/reference/storage/external-ceph-guide.html).

- include_tasks: "{{ kolla_action }}.yml"
