---
- name: Cloning neutron source repository for development
  git:
    repo: "{{ neutron_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ neutron_dev_repos_pull }}"
    version: "{{ neutron_source_version }}"
