---
- include_tasks: register.yml
  when: inventory_hostname in groups['neutron-server']

- include_tasks: clone.yml
  when: neutron_dev_mode | bool

- include_tasks: config.yml

- include_tasks: config-neutron-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['neutron-server']

- name: Flush Handlers
  meta: flush_handlers
