---
- include_tasks: config.yml

- include_tasks: config-neutron-fake.yml
  when:
    - inventory_hostname in groups['compute']
    - enable_nova_fake | bool

- include_tasks: bootstrap_service.yml

- name: Flush Handlers
  meta: flush_handlers
