---
# TODO(mgoddard): Remove this in U cycle once all old containers have been
# stopped.
- name: Stopping old neutron-lbaas-agent containers
  become: true
  kolla_docker:
    action: "stop_and_remove_container"
    common_options: "{{ docker_common_options }}"
    name: "neutron_lbaas_agent"

- include_tasks: rolling_upgrade.yml
  when: neutron_enable_rolling_upgrade | bool

- include_tasks: legacy_upgrade.yml
  when: not neutron_enable_rolling_upgrade | bool
