---
- name: Cloning congress source repository for development
  git:
    repo: "{{ congress_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ congress_dev_repos_pull }}"
    version: "{{ congress_source_version }}"
