---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ congress_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: congress_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/congress/"
      skip: true

- name: Set congress policy file
  set_fact:
    congress_policy_file: "{{ congress_policy.results.0.stat.path | basename }}"
    congress_policy_file_path: "{{ congress_policy.results.0.stat.path }}"
  when:
    - congress_policy.results

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ congress_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over congress.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/congress.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/congress.conf"
      - "{{ node_custom_config }}/congress/{{ item.key }}.conf"
      - "{{ node_custom_config }}/congress/{{ inventory_hostname }}/congress.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/congress.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ congress_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over existing policy file
  template:
    src: "{{ congress_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ congress_policy_file }}"
    mode: "0660"
  become: true
  when:
    - congress_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ congress_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Check congress containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
    dimensions: "{{ item.value.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ congress_services }}"
  notify:
    - "Restart {{ item.key }} container"
