---
- include_tasks: config.yml

- include_tasks: clone.yml
  when:
    - horizon_dev_mode | bool

- include_tasks: bootstrap_service.yml
  when: horizon_backend_database | bool

- name: Flush handlers
  meta: flush_handlers
