---
- include_tasks: register.yml
  when: inventory_hostname in groups['vitrage-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['vitrage-api'] or
        inventory_hostname in groups['vitrage-ml'] or
        inventory_hostname in groups['vitrage-graph'] or
        inventory_hostname in groups['vitrage-notifier']

- include_tasks: clone.yml
  when: vitrage_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['vitrage-api']

- name: Flush handlers
  meta: flush_handlers
