---
- name: Creating the Vitrage service and endpoint
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_service"
    module_args:
      service_name: "vitrage"
      service_type: "rca"
      description: "Root Cause Analysis Service"
      endpoint_region: "{{ openstack_region_name }}"
      url: "{{ item.url }}"
      interface: "{{ item.interface }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_vitrage_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ vitrage_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ vitrage_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ vitrage_public_endpoint }}'}

- name: Creating the Vitrage project, user, and role
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_user"
    module_args:
      project: "service"
      user: "{{ vitrage_keystone_user }}"
      password: "{{ vitrage_keystone_password }}"
      role: "admin"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_vitrage_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True

- name: Adding vitrage user into admin project
  become: true
  kolla_toolbox:
    module_name: "os_user_role"
    module_args:
      user: "{{ vitrage_keystone_user }}"
      role: "admin"
      project: "admin"
      auth: "{{ openstack_vitrage_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
