---
- name: Check nova upgrade status
  become: true
  command: docker exec -t nova_api nova-status upgrade check
  register: nova_upgrade_check_stdout
  when: inventory_hostname == groups['nova-api'][0]

- name: Upgrade status check result
  fail:
    msg:
      - "There was an upgrade status check warning or failure!"
      - "See the detail at https://docs.openstack.org/nova/latest/cli/nova-status.html#nova-status-checks"
  vars:
    first_nova_api_host: "{{ groups['nova-api'][0] }}"
  when: hostvars[first_nova_api_host]['nova_upgrade_check_stdout']['rc'] != 0

- include_tasks: legacy_upgrade.yml
  when: not nova_enable_rolling_upgrade | bool

- include_tasks: rolling_upgrade.yml
  when: nova_enable_rolling_upgrade | bool

# NOTE(jeffrey4l): Remove this task in U cycle.
- name: Remove nova-consoleauth container
  become: true
  kolla_docker:
    action: "remove_container"
    name: "nova_consoleauth"
