---
- name: Load and persist dm-multipath module
  import_role:
    role: module-load
  vars:
    modules:
      - {'name': dm-multipath}

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ multipathd_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ multipathd_services }}"
  notify:
    - Restart multipathd container

- name: Copying over multipath.conf
  template:
    src: "multipath.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/multipath.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ multipathd_services }}"
  notify:
    - Restart multipathd container

- name: Check multipathd containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    ipc_mode: "{{ item.value.ipc_mode }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ multipathd_services }}"
  notify:
    - Restart multipathd container
