---
project_name: "murano"

murano_services:
  murano-api:
    container_name: murano_api
    group: murano-api
    enabled: true
    image: "{{ murano_api_image_full }}"
    volumes: "{{ murano_api_default_volumes + murano_api_extra_volumes }}"
    dimensions: "{{ murano_api_dimensions }}"
    haproxy:
      murano_api:
        enabled: "{{ enable_murano }}"
        mode: "http"
        external: false
        port: "{{ murano_api_port }}"
      murano_api_external:
        enabled: "{{ enable_murano }}"
        mode: "http"
        external: true
        port: "{{ murano_api_port }}"
  murano-engine:
    container_name: murano_engine
    group: murano-engine
    enabled: true
    image: "{{ murano_engine_image_full }}"
    volumes: "{{ murano_engine_default_volumes + murano_engine_extra_volumes }}"
    dimensions: "{{ murano_engine_dimensions }}"


####################
# Database
####################
murano_database_name: "murano"
murano_database_user: "{% if use_preconfigured_databases | bool and use_common_mariadb_user | bool %}{{ database_user }}{% else %}murano{% endif %}"
murano_database_address: "{{ database_address }}:{{ database_port }}"


####################
# Docker
####################
murano_install_type: "{{ kolla_install_type }}"
murano_tag: "{{ openstack_release }}"

murano_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ murano_install_type }}-murano-api"
murano_api_tag: "{{ murano_tag }}"
murano_api_image_full: "{{ murano_api_image }}:{{ murano_api_tag }}"

murano_engine_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ murano_install_type }}-murano-engine"
murano_engine_tag: "{{ murano_tag }}"
murano_engine_image_full: "{{ murano_engine_image }}:{{ murano_engine_tag }}"

murano_api_dimensions: "{{ default_container_dimensions }}"
murano_engine_dimensions: "{{ default_container_dimensions }}"

murano_api_default_volumes:
  - "{{ node_config_directory }}/murano-api/:{{ container_config_directory }}/:ro"
  - "{{ kolla_dev_repos_directory ~ '/murano/murano:/var/lib/kolla/venv/lib/python2.7/site-packages/murano' if murano_dev_mode | bool else '' }}"
  - "/etc/localtime:/etc/localtime:ro"
  - "kolla_logs:/var/log/kolla/"
murano_engine_default_volumes:
  - "{{ node_config_directory }}/murano-engine/:{{ container_config_directory }}/:ro"
  - "{{ kolla_dev_repos_directory ~ '/murano/murano:/var/lib/kolla/venv/lib/python2.7/site-packages/murano' if murano_dev_mode | bool else '' }}"
  - "/etc/localtime:/etc/localtime:ro"
  - "kolla_logs:/var/log/kolla/"

murano_extra_volumes: "{{ default_extra_volumes }}"
murano_api_extra_volumes: "{{ murano_extra_volumes }}"
murano_engine_extra_volumes: "{{ murano_extra_volumes }}"

####################
# OpenStack
####################
murano_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ murano_api_port }}"
murano_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ murano_api_port }}"
murano_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ murano_api_port }}"

murano_logging_debug: "{{ openstack_logging_debug }}"

openstack_murano_auth: "{{ openstack_auth }}"

murano_agent_timeout: 3600

####################
# Kolla
####################
murano_git_repository: "{{ kolla_dev_repos_git }}/{{ project_name }}"
murano_dev_repos_pull: "{{ kolla_dev_repos_pull }}"
murano_dev_mode: "{{ kolla_dev_mode }}"
murano_source_version: "{{ kolla_source_version }}"
