---
- name: Creating the Kuryr project, user, and role
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_user"
    module_args:
      project: "service"
      user: "{{ kuryr_keystone_user }}"
      password: "{{ kuryr_keystone_password }}"
      role: "admin"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_kuryr_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
