---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ storm_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ storm_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over storm worker config
  vars:
    service: "{{ storm_services['storm-worker'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/storm-worker/storm.yml"
    mode: "0660"
  become: true
  with_first_found:
    - "{{ node_custom_config }}/storm/{{ inventory_hostname }}/storm.yml"
    - "{{ node_custom_config }}/storm.yml"
    - "storm.yml.j2"
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart storm-worker container

- name: Copying over storm nimbus config
  vars:
    service: "{{ storm_services['storm-nimbus'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/storm-nimbus/storm.yml"
    mode: "0660"
  become: true
  with_first_found:
    - "{{ node_custom_config }}/storm/{{ inventory_hostname }}/storm.yml"
    - "{{ node_custom_config }}/storm.yml"
    - "storm.yml.j2"
  when:
    - inventory_hostname in groups[service['group']]
    - service.enabled | bool
  notify:
    - Restart storm-nimbus container

- name: Check storm containers
  become: true
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    environment: "{{ item.value.environment }}"
    dimensions: "{{ item.value.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ storm_services }}"
  notify:
    - "Restart {{ item.key }} container"
