---
project_name: "skydive"

skydive_services:
  skydive-analyzer:
    container_name: skydive_analyzer
    group: skydive-analyzer
    enabled: true
    image: "{{ skydive_analyzer_image_full }}"
    volumes:
      - "{{ node_config_directory }}/skydive-analyzer/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
    dimensions: "{{ skydive_analyzer_dimensions }}"
    haproxy:
      skydive_server:
        enabled: "{{ enable_skydive }}"
        mode: "http"
        external: false
        port: "{{ skydive_analyzer_port }}"
      skydive_server_external:
        enabled: "{{ enable_skydive }}"
        mode: "http"
        external: true
        port: "{{ skydive_analyzer_port }}"
  skydive-agent:
    container_name: skydive_agent
    group: skydive-agent
    enabled: true
    image: "{{ skydive_agent_image_full }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/skydive-agent/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/openvswitch:/var/run/openvswitch:ro"
      - "/var/run/netns:/host/run:shared"
      - "kolla_logs:/var/log/kolla/"
    dimensions: "{{ skydive_agent_dimensions }}"

####################
# Docker
####################
skydive_analyzer_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-skydive-analyzer"
skydive_analyzer_tag: "{{ openstack_release }}"
skydive_analyzer_image_full: "{{ skydive_analyzer_image }}:{{ skydive_analyzer_tag }}"

skydive_agent_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-skydive-agent"
skydive_agent_tag: "{{ openstack_release }}"
skydive_agent_image_full: "{{ skydive_agent_image }}:{{ skydive_agent_tag }}"
skydive_analyzer_dimensions: "{{ default_container_dimensions }}"
skydive_agent_dimensions: "{{ default_container_dimensions }}"
