---
- name: Cloning qinling source repository for development
  git:
    repo: "{{ qinling_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ qinling_dev_repos_pull }}"
    version: "{{ qinling_source_version }}"
