---
- name: Creating the Qinling service and endpoint
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_service"
    module_args:
      service_name: "qinling"
      service_type: "function-engine"
      description: "Function Service"
      endpoint_region: "{{ openstack_region_name }}"
      url: "{{ item.url }}"
      interface: "{{ item.interface }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_qinling_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ qinling_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ qinling_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ qinling_public_endpoint }}'}

- name: Creating the Qinling project, user, and role
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_user"
    module_args:
      project: "service"
      user: "{{ qinling_keystone_user }}"
      password: "{{ qinling_keystone_password }}"
      role: "admin"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_qinling_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
