---
- include_tasks: register.yml
  when: inventory_hostname in groups['magnum-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['magnum-api'] or
        inventory_hostname in groups['magnum-conductor']

- include_tasks: clone.yml
  when: magnum_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['magnum-api']

- name: Flush handlers
  meta: flush_handlers
