---
- include_tasks: register.yml
  when: inventory_hostname in groups['monasca-agent'] or
        inventory_hostname in groups['monasca-api'] or
        inventory_hostname in groups['monasca-log-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['monasca-agent'] or
        inventory_hostname in groups['monasca-api'] or
        inventory_hostname in groups['monasca-grafana'] or
        inventory_hostname in groups['monasca-log-api'] or
        inventory_hostname in groups['monasca-log-transformer'] or
        inventory_hostname in groups['monasca-log-persister'] or
        inventory_hostname in groups['monasca-log-metrics'] or
        inventory_hostname in groups['monasca-thresh'] or
        inventory_hostname in groups['monasca-notification'] or
        inventory_hostname in groups['monasca-persister']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['monasca-api'] or
        inventory_hostname in groups['monasca-grafana']

- name: Flush handlers
  meta: flush_handlers

- include_tasks: check.yml
  when: inventory_hostname in groups['monasca-agent'] or
        inventory_hostname in groups['monasca-api'] or
        inventory_hostname in groups['monasca-grafana'] or
        inventory_hostname in groups['monasca-log-api'] or
        inventory_hostname in groups['monasca-log-transformer'] or
        inventory_hostname in groups['monasca-log-persister'] or
        inventory_hostname in groups['monasca-log-metrics'] or
        inventory_hostname in groups['monasca-thresh'] or
        inventory_hostname in groups['monasca-notification'] or
        inventory_hostname in groups['monasca-persister']

- include_tasks: post_config.yml
