---
- include_tasks: register.yml
  when: inventory_hostname in groups['aodh-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['aodh-api'] or
        inventory_hostname in groups['aodh-evaluator'] or
        inventory_hostname in groups['aodh-listener'] or
        inventory_hostname in groups['aodh-notifier']

- include_tasks: clone.yml
  when: aodh_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['aodh-api']

- name: Flush handlers
  meta: flush_handlers
