---
- include_tasks: register.yml
  when: inventory_hostname in groups['cinder-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['ceph-mon'] or
        inventory_hostname in groups['cinder-api'] or
        inventory_hostname in groups['cinder-volume'] or
        inventory_hostname in groups['cinder-scheduler'] or
        inventory_hostname in groups['cinder-backup']

- include_tasks: clone.yml
  when: cinder_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['cinder-api']

- name: Flush handlers
  meta: flush_handlers

- include_tasks: check.yml
  when: inventory_hostname in groups['cinder-api'] or
        inventory_hostname in groups['cinder-volume'] or
        inventory_hostname in groups['cinder-scheduler'] or
        inventory_hostname in groups['cinder-backup']
