---
- include_tasks: register.yml
  when: inventory_hostname in groups['barbican-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['barbican-api'] or
        inventory_hostname in groups['barbican-worker'] or
        inventory_hostname in groups['barbican-keystone-listener']

- include_tasks: clone.yml
  when: barbican_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['barbican-api']

- name: Flush handlers
  meta: flush_handlers
