---
- name: Copying over ceph.conf(s)
  merge_configs:
    sources:
      - "{{ role_path }}/../ceph/templates/ceph.conf.j2"
      - "{{ node_custom_config }}/ceph.conf"
      - "{{ node_custom_config }}/ceph/{{ inventory_hostname }}/ceph.conf"
    dest: "{{ node_config_directory }}/{{ item }}/ceph.conf"
    mode: "0660"
  become: true
  when: inventory_hostname in groups[item]
  with_items:
    - "gnocchi-api"
    - "gnocchi-metricd"
    - "gnocchi-statsd"
  notify:
    - Restart {{ item }} container

- include_tasks: ../../ceph_pools.yml
  vars:
    pool_name: "{{ gnocchi_pool_name }}"
    pool_type: "{{ gnocchi_pool_type }}"
    cache_mode: "{{ gnocchi_cache_mode }}"
    pool_pg_num: "{{ gnocchi_pool_pg_num }}"
    pool_pgp_num: "{{ gnocchi_pool_pgp_num }}"
    pool_application: "rgw"

- name: Pulling cephx keyring
  become: true
  kolla_ceph_keyring:
    name: client.gnocchi
    caps: "{{ ceph_client_gnocchi_keyring_caps }}"
  register: cephx_key
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  run_once: True

- name: Pushing cephx keyring
  copy:
    content: |
      [client.gnocchi]
          key = {{ cephx_key.keyring.key }}
    dest: "{{ node_config_directory }}/{{ item }}/ceph.client.gnocchi.keyring"
    mode: "0600"
  become: true
  when: inventory_hostname in groups[item]
  with_items:
    - "gnocchi-api"
    - "gnocchi-metricd"
    - "gnocchi-statsd"
  notify:
    - Restart {{ item }} container
