---
- name: Copy over ceph.conf file
  template:
    src: "{{ node_custom_config }}/gnocchi/ceph.conf"
    dest: "{{ node_config_directory }}/{{ item }}/ceph.conf"
    mode: "0660"
  become: true
  when: inventory_hostname in groups[item]
  with_items:
    - "gnocchi-api"
    - "gnocchi-metricd"
    - "gnocchi-statsd"
  notify:
    - Restart {{ item }} container

- name: Copy over ceph gnocchi keyring
  copy:
    src: "{{ node_custom_config }}/gnocchi/ceph.client.gnocchi.keyring"
    dest: "{{ node_config_directory }}/{{ item }}/ceph.client.gnocchi.keyring"
    mode: "0660"
  become: true
  when: inventory_hostname in groups[item]
  with_items:
    - "gnocchi-api"
    - "gnocchi-metricd"
    - "gnocchi-statsd"
  notify:
    - Restart {{ item }} container

- name: Ensuring config directory has correct owner and permission
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  when: inventory_hostname in groups[item]
  with_items:
    - "gnocchi-api"
    - "gnocchi-metricd"
    - "gnocchi-statsd"
