---
- name: Copying over ceph.conf for manila
  merge_configs:
    sources:
      - "{{ role_path }}/../ceph/templates/ceph.conf.j2"
      - "{{ node_custom_config }}/ceph.conf"
      - "{{ node_custom_config }}/ceph/{{ inventory_hostname }}/ceph.conf"
    dest: "{{ node_config_directory }}/manila-share/ceph.conf"
    mode: "0660"
  become: true
  notify:
    - Restart manila-share container

- name: Pulling cephx keyring for manila
  become: true
  kolla_ceph_keyring:
    name: client.manila
    caps: "{{ ceph_client_manila_keyring_caps }}"
  register: cephx_key_manila
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  run_once: True

- name: Pushing cephx keyring
  copy:
    content: |
      [client.manila]
          key = {{ cephx_key_manila.keyring.key }}
    dest: "{{ node_config_directory }}/manila-share/ceph.client.manila.keyring"
    mode: "0600"
  become: true
  notify:
    - Restart manila-share container
