---
- include_tasks: clone.yml
  when: manila_dev_mode | bool

- include_tasks: register.yml
  when: inventory_hostname in groups['manila-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['manila-api'] or
        inventory_hostname in groups['manila-data'] or
        inventory_hostname in groups['manila-share'] or
        inventory_hostname in groups['manila-scheduler']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['manila-api']

- name: Flush handlers
  meta: flush_handlers

- include_tasks: fix_cephfs_owner.yml
  when:
    - not enable_ceph | bool or enable_ceph_mds | bool
    - enable_manila_backend_cephfs_native | bool
    - inventory_hostname in groups['manila-share']
