---
project_name: "elasticsearch"

elasticsearch_services:
  elasticsearch:
    container_name: elasticsearch
    group: elasticsearch
    enabled: true
    image: "{{ elasticsearch_image_full }}"
    environment:
      ES_JAVA_OPTS: "{{ es_java_opts }}"
    volumes:
      - "{{ node_config_directory }}/elasticsearch/:{{ container_config_directory }}/"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ elasticsearch_datadir_volume }}:/var/lib/elasticsearch/data"
    dimensions: "{{ elasticsearch_dimensions }}"
    haproxy:
      elasticsearch:
        enabled: "{{ enable_elasticsearch }}"
        mode: "http"
        external: false
        port: "{{ elasticsearch_port }}"
        frontend_http_extra:
          - "option dontlog-normal"


####################
# Elasticsearch
####################
elasticsearch_cluster_name: "kolla_logging"
es_heap_size: "1g"
es_java_opts: "{% if es_heap_size %}-Xms{{ es_heap_size }} -Xmx{{ es_heap_size }}{%endif%}"

####################
# Docker
####################
elasticsearch_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-elasticsearch"
elasticsearch_tag: "{{ openstack_release }}"
elasticsearch_image_full: "{{ elasticsearch_image }}:{{ elasticsearch_tag }}"

elasticsearch_dimensions: "{{ default_container_dimensions }}"
