---
- include_tasks: register.yml
  when: inventory_hostname in groups['tacker-server']

- include_tasks: config.yml
  when: inventory_hostname in groups['tacker-server'] or
        inventory_hostname in groups['tacker-conductor']

- include_tasks: clone.yml
  when:
    - tacker_dev_mode | bool
    - inventory_hostname in groups['tacker-server'] or
      inventory_hostname in groups['tacker-conductor']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['tacker-server']

- name: Flush handlers
  meta: flush_handlers
