---
- include_tasks: register.yml
  when: inventory_hostname in groups['solum-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['solum-api'] or
        inventory_hostname in groups['solum-deploy'] or
        inventory_hostname in groups['solum-worker'] or
        inventory_hostname in groups['solum-conductor']

- include_tasks: clone.yml
  when: solum_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['solum-api']

- name: Flush handlers
  meta: flush_handlers
