---
- name: Restart opendaylight container
  vars:
    service_name: "opendaylight"
    service: "{{ opendaylight_services[service_name] }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    privileged: "{{ service.privileged | default(False) }}"
    dimensions: "{{ service.dimensions }}"
    tty: "{{ service.tty }}"
  when:
    - kolla_action != "config"
