---
- import_playbook: detect-release.yml
  vars:
    detect_release_hosts: mariadb

- name: Recover mariadb
  hosts: mariadb
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: enable_mariadb | bool }
  vars:
    mariadb_recover: true
