---
- name: Creating admin openrc file on the deploy node
  hosts: localhost
  become: true
  tasks:
    - template:
        src: "roles/common/templates/admin-openrc.sh.j2"
        dest: "{{ node_config }}/admin-openrc.sh"
      run_once: True
