---
- name: Cloning zun source repository for development
  git:
    repo: "{{ zun_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ zun_dev_repos_pull }}"
    version: "{{ zun_source_version }}"
