---
- include_tasks: register.yml
  when: inventory_hostname in groups['zun-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['zun-api'] or
        inventory_hostname in groups['zun-compute']

- include_tasks: clone.yml
  when: zun_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['zun-api']

- name: Flush handlers
  meta: flush_handlers
