---
- project:
    templates:
      - check-requirements
      - deploy-guide-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-ubuntu-source-ceph
        - kolla-ansible-centos-source-ceph
        - kolla-ansible-ubuntu-source-cinder-lvm:
            files: ^ansible\/roles\/(cinder|iscsi)\/.*
        - kolla-ansible-centos-source-cinder-lvm:
            files: ^ansible\/roles\/(cinder|iscsi)\/.*
        - kolla-ansible-bifrost-centos-source:
            files: ^ansible\/roles\/bifrost\/.*
        - kolla-ansible-ubuntu-source-zun:
            files: ^ansible\/roles\/(zun|kuryr)\/.*
        - kolla-ansible-centos-source-scenario-nfv:
            files: ^ansible\/roles\/(barbican|heat|mistral|redis|tacker)\/.*
        - kolla-ansible-centos-source-ironic
        - kolla-ansible-centos-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-source-upgrade-ceph
        - kolla-ansible-ubuntu-source-upgrade-ceph
        - kolla-ansible-centos-binary
        - kolla-ansible-ubuntu-binary
    gate:
      queue: kolla
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
    periodic:
      jobs:
        - kolla-ansible-bifrost-centos-source
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-centos-source-scenario-nfv
        - kolla-ansible-ubuntu-source-cinder-lvm
        - kolla-ansible-centos-source-cinder-lvm
        - kolla-ansible-centos-source-ironic
        - kolla-ansible-centos-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-source-upgrade-ceph
        - kolla-ansible-ubuntu-source-upgrade-ceph
