---
- name: Creating the cyborg service and endpoint
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_service"
    module_args:
      service_name: "cyborg"
      service_type: "cyborg"
      description: "OpenStack Cyborg Service"
      endpoint_region: "{{ openstack_region_name }}"
      url: "{{ item.url }}"
      interface: "{{ item.interface }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_cyborg_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ cyborg_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ cyborg_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ cyborg_public_endpoint }}'}

- name: Creating the cyborg project, user, and role
  become: true
  kolla_toolbox:
    module_name: "kolla_keystone_user"
    module_args:
      project: "service"
      user: "{{ cyborg_keystone_user }}"
      password: "{{ cyborg_keystone_password }}"
      role: "admin"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_cyborg_auth }}"
      endpoint_type: "{{ openstack_interface }}"
  run_once: True
