---
- include_tasks: register.yml
  when: inventory_hostname in groups['heat-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['heat-api'] or
        inventory_hostname in groups['heat-api-cfn'] or
        inventory_hostname in groups['heat-engine']

- include_tasks: clone.yml
  when:
    - heat_dev_mode | bool
    - inventory_hostname in groups['heat-api'] or
      inventory_hostname in groups['heat-api-cfn'] or
      inventory_hostname in groups['heat-engine']

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['heat-api']

- name: Flush handlers
  meta: flush_handlers
