---
- name: Enrolling physical servers with ironic
  become: true
  command: >
     docker exec bifrost_deploy
     bash -c 'source /bifrost/env-vars &&
     export BIFROST_INVENTORY_SOURCE=/etc/bifrost/servers.yml &&
     ansible-playbook -vvvv -i /bifrost/playbooks/inventory/bifrost_inventory.py
     /bifrost/playbooks/enroll-dynamic.yaml -e @/etc/bifrost/bifrost.yml'

- name: Deploy physical servers with ironic
  become: true
  command: >
     docker exec bifrost_deploy
     bash -c 'source /bifrost/env-vars &&
     export BIFROST_INVENTORY_SOURCE=/etc/bifrost/servers.yml &&
     ansible-playbook -vvvv -i /bifrost/playbooks/inventory/bifrost_inventory.py
     /bifrost/playbooks/deploy-dynamic.yaml -e @/etc/bifrost/bifrost.yml'
