---
- include_tasks: register.yml
  when: inventory_hostname in groups['mistral-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['mistral-api'] or
        inventory_hostname in groups['mistral-engine'] or
        inventory_hostname in groups['mistral-event-engne'] or
        inventory_hostname in groups['mistral-executor']

- include_tasks: clone.yml
  when: mistral_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['mistral-api']

- name: Flush handlers
  meta: flush_handlers
