---
- name: Cloning designate source repository for development
  git:
    repo: "{{ designate_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ designate_dev_repos_pull }}"
    version: "{{ designate_source_version }}"
