---
- include_tasks: register.yml
  when: inventory_hostname in groups['designate-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['designate-api'] or
        inventory_hostname in groups['designate-central'] or
        inventory_hostname in groups['designate-producer'] or
        inventory_hostname in groups['designate-mdns'] or
        inventory_hostname in groups['designate-worker'] or
        inventory_hostname in groups['designate-sink'] or
        inventory_hostname in groups['designate-backend-bind9']

- include_tasks: clone.yml
  when: designate_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['designate-central']

- name: Flush handlers
  meta: flush_handlers

- include_tasks: update_pools.yml
  when: inventory_hostname == groups['designate-worker'][0]
