---
- name: Update DNS pools
  become: true
  command: docker exec -t designate_worker designate-manage pool update --file /etc/designate/pools.yaml
  when: inventory_hostname == groups['designate-worker'][0]
